import numpy as np
from parse import data as parse
from scipy.signal import find_peaks as fp
import scipy.fft as fft

#---------------------------------------------------------------------#
#   bifurcation.py                                                    #
#                                                                     #
#   DESCRIPTION                                                       #
#   Reads .bin data generated by a SIGLENT SDS2352X-E Oscilloscope    #
#   Returns the bifurcation values given a FILEPATH string            #
#                                                                     #
#   USAGE                                                             #
#   [ENSURE THAT BOTH THE REQUIREMENTS AND THIS SCRIPT                #
#    ARE IN THE SAME DIRECTORY]                                       #
#   import bifurcation as BF                                          #
#   RV_AMPLITUDES = BF.GETAMPLITUDES("FILEPATH")                      #
#                                                                     #
#   REQUIREMENTS                                                      #
#   Requires the parse.py script also by Jayson Wu                    #
#                                                                     #
#   Author: JAYSON WU                                                 #
#   Last Modified: February 26th, 2026                                #
#---------------------------------------------------------------------#

# Removes consecutive minimum / maximum points from the conjoined array of maximum and minimum indices
def FIX(MAXES,MINS):
    ALL = (np.sort(np.append(MAXES,MINS)))
    INDICES = np.array([])
    REMOVE = np.array([],dtype=np.int32)
    for i in range(len(ALL)):
        temp = np.argwhere(MAXES == ALL[i])
        if (temp.size != 0):
            INDICES = np.append(INDICES,1)
        temp = np.argwhere(MINS == ALL[i])
        if (temp.size != 0):
            INDICES = np.append(INDICES,0)
    for i in range(len(INDICES)-1):
        if (INDICES[i] == INDICES[i+1]):
            REMOVE = np.append(REMOVE, i)
    ALL = np.delete(ALL, np.flip(REMOVE))
    return ALL


# Returns the amplitudes without error correction - both negative and positive amplitude values exist
def AMPLITUDES(DATA,INDICES):
    AMPS = np.array([])
    for i in range(INDICES.size-1):
        TEMP = ((DATA[INDICES[i+1]]) - (DATA[INDICES[i]]))
        if (TEMP > 0):
            AMPS = np.append(AMPS, TEMP)
    return AMPS

# With a given FILEPATH string, assuming that the requested data was on CHANNEL 1, returns the BIFURCATION values
# Rv value is not given / dependent. That is up to the user.
def GETAMPLITUDES(FILEPATH):
    CH1,CH2,T = parse(open(FILEPATH,"rb"))
    CH1*=10.0
    FREQS = fft.rfftfreq(CH1.size,T[1])
    temp = np.argwhere(FREQS>0)
    FREQS = np.log10(FREQS[temp]).ravel()
    temp = np.argwhere((FREQS<3.7)&(FREQS>1.5))
    FREQS = FREQS[temp].ravel()
    FFT = np.log10(np.abs(fft.rfft(CH1))[temp]).ravel()
    temp = fp(FFT,prominence=1)[0]
    FREQS = 10**(FREQS[temp])
    # TEMPARRAY = FREQS*FFT[temp]
    WAVGF = np.average(FREQS)
    # WAVGF = np.sum(TEMPARRAY)/np.sum(FFT[temp])
    SPACE = len(CH1)/(WAVGF*T[-1])
    NCH1 = -CH1
    NCH1 -= np.min(NCH1)
    N = fp(CH1,distance=SPACE/1.5)[0]
    M = fp(NCH1,distance=SPACE/1.5)[0]
    INDICES = FIX(N,M)[1:-1]
    DATA = AMPLITUDES(CH1,INDICES)
    return DATA

def SIMAMPLITUDES(DATA,T):
    FREQS = fft.rfftfreq(DATA.size,0.01)
    temp = np.argwhere(FREQS>0)
    FREQS = np.log10(FREQS[temp]).ravel()
    temp = np.argwhere((FREQS<3.7)&(FREQS>1.5))
    FREQS = FREQS[temp].ravel()
    FFT = np.log10(np.abs(fft.rfft(DATA))[temp]).ravel()
    temp = fp(FFT,prominence=1)[0]
    FREQS = 10**(FREQS[temp])
    TEMPARRAY = FREQS*FFT[temp]
    WAVGF = np.average(FREQS)
    WAVGF = np.sum(TEMPARRAY)/np.sum(FFT[temp])
    SPACE = len(DATA)/(WAVGF*20e-3)
    NCH1 = -DATA
    NCH1 -= np.min(NCH1)
    N = fp(DATA,distance=SPACE/1.5)[0]
    M = fp(NCH1,distance=SPACE/1.5)[0]
    INDICES = FIX(N,M)[1:-1]
    DATA = AMPLITUDES(DATA,INDICES)
    return DATA