import numpy as np
import struct

#---------------------------------------------------------------------#
#   parse.py                                                          #
#                                                                     #
#   DESCRIPTION                                                       #
#   Reads .bin data generated by a SIGLENT SDS2352X-E Oscilloscope    #
#   Returns data from channels 1 & 2 along with respective time data  #
#                                                                     #
#   USAGE                                                             #
#   from parse import data as parse                                   #
#   file = open(PATH_TO_FILE,"rb")                                    #
#   ch1,ch2,t = parse(file)                                           #
#                                                                     #
#   Author: JAYSON WU                                                 #
#   Last Modified: February 13th, 2026                                #
#---------------------------------------------------------------------#

# const parameters
ngrid = 14.0    # 14 grids horizontally on the oscilloscope screen
cpdiv = 25.0    # 25 data codes per div

# unit magnitude dictionary
mag = {
    5:1e-9,
    6:1e-6,
    7:1e-3,
    8:1e0,
    9:1e3,
    10:1e6,
    11:1e9
}


# Given a opened file variable, returns 3 numpy arrays of data without probe magnification
def data(file):
    t = np.array([])
    ch1 = np.array([])
    ch2 = np.array([])
    file.seek(0x0,0)
    state1 = struct.unpack('<i',file.read(0x4))[0]
    file.seek(0x4,0)
    state2 = struct.unpack('<i',file.read(0x4))[0]
    
    file.seek(0xd4,0)
    tdiv = struct.unpack('<d',file.read(0x8))[0]
    file.seek(0xdc,0)
    tmag = mag[struct.unpack('<i',file.read(0x4))[0]]
    tdiv *= tmag
    
    file.seek(0xf4,0)
    wavelength = struct.unpack('<i',file.read(0x4))[0]
    narray = np.linspace(0,wavelength,wavelength)
    
    file.seek(0xf8,0)
    samplerate = struct.unpack('<d',file.read(0x8))[0]
    file.seek(0x100,0)
    sampleratemag = mag[struct.unpack('<i',file.read(0x4))[0]]
    samplerate *= sampleratemag
    
    if (state1 == 1):
        file.seek(0x10,0)
        ch1div = struct.unpack('<d',file.read(0x8))[0]
        file.seek(0x18,0)
        ch1mag = mag[struct.unpack('<i',file.read(0x4))[0]]
        ch1div *= ch1mag
        file.seek(0x800,0)
        ch1 = np.int8(np.fromfile(file,dtype=np.uint8,count=wavelength,offset=0)-128)*(ch1div/cpdiv)
    
    if (state2 == 1):
        file.seek(0x20,0)
        ch2div = struct.unpack('<d',file.read(0x8))[0]
        file.seek(0x28,0)
        ch2mag = mag[struct.unpack('<i',file.read(0x4))[0]]
        ch2div *= ch2mag
        offset = 0x800
        file.seek(0x800,0)
        if (state1 == 1):
            file.seek(wavelength,1)
        ch2 = np.int8(np.fromfile(file,dtype=np.uint8,count=wavelength)-128)*(ch2div/cpdiv)
        
    t = -(tdiv*ngrid/2)+narray*(1/samplerate)
    
    return ch1,ch2,t