import numpy as np
import scipy.fft as fft
import struct

#---------------------------------------------------------------------#
#   chaoticPackage.py                                                 #
#                                                                     #
#   DESCRIPTION                                                       #
#   Reads .bin data generated by a SIGLENT SDS2352X-E Oscilloscope    #
#   Returns the either:                                               #
#   Amplitude data                                                    #
#   Power Spectrum frequency/magnitude data                           #
#   Channels 1,2 and time data                                        #
#                                                                     #
#   USAGE                                                             #
#   [ENSURE THAT BOTH THE REQUIREMENTS AND THIS SCRIPT                #
#    ARE IN THE SAME DIRECTORY]                                       #
#   import chaoticPackage as cp                                       #
#   amplitudes = cp.getAmplitudes("FILEPATH")                         #
#   freq,mag = cp.getSpectrum("FILEPATH")                             #
#   amplitudes = cp.getData("FILEPATH")                               #
#                                                                     #
#                                                                     #
#   Author: JAYSON WU                                                 #
#   Last Modified: March 5th, 2026                                    #
#---------------------------------------------------------------------#

# const parameters
ngrid = 14.0    # 14 grids horizontally on the oscilloscope screen
cpdiv = 25.0    # 25 data codes per div

# unit magnitude dictionary
mag = {
    5:1e-9,
    6:1e-6,
    7:1e-3,
    8:1e0,
    9:1e3,
    10:1e6,
    11:1e9
}

# Given a filepath string, returns 3 numpy arrays of data without probe magnification
def readFile(FILEPATH):
    file = open(FILEPATH,"rb")
    t = np.array([])
    ch1 = np.array([])
    ch2 = np.array([])
    file.seek(0x0,0)
    state1 = struct.unpack('<i',file.read(0x4))[0]
    file.seek(0x4,0)
    state2 = struct.unpack('<i',file.read(0x4))[0]
    
    file.seek(0xd4,0)
    tdiv = struct.unpack('<d',file.read(0x8))[0]
    file.seek(0xdc,0)
    tmag = mag[struct.unpack('<i',file.read(0x4))[0]]
    tdiv *= tmag
    
    file.seek(0xf4,0)
    wavelength = struct.unpack('<i',file.read(0x4))[0]
    narray = np.linspace(0,wavelength,wavelength)
    
    file.seek(0xf8,0)
    samplerate = struct.unpack('<d',file.read(0x8))[0]
    file.seek(0x100,0)
    sampleratemag = mag[struct.unpack('<i',file.read(0x4))[0]]
    samplerate *= sampleratemag
    
    if (state1 == 1):
        file.seek(0x10,0)
        ch1div = struct.unpack('<d',file.read(0x8))[0]
        file.seek(0x18,0)
        ch1mag = mag[struct.unpack('<i',file.read(0x4))[0]]
        ch1div *= ch1mag
        file.seek(0x800,0)
        ch1 = np.int8(np.fromfile(file,dtype=np.uint8,count=wavelength,offset=0)-128)*(ch1div/cpdiv)
        file.seek(0x50,0)
        ch1off = struct.unpack('<d',file.read(0x8))[0]
        ch1 += ch1off
    
    if (state2 == 1):
        file.seek(0x20,0)
        ch2div = struct.unpack('<d',file.read(0x8))[0]
        file.seek(0x28,0)
        ch2mag = mag[struct.unpack('<i',file.read(0x4))[0]]
        ch2div *= ch2mag
        file.seek(0x800,0)
        if (state1 == 1):
            file.seek(wavelength,1)
        ch2 = np.int8(np.fromfile(file,dtype=np.uint8,count=wavelength)-128)*(ch2div/cpdiv)
        file.seek(0x60,0)
        ch2off = struct.unpack('<d',file.read(0x8))[0]
        ch2 += ch2off
        
    t = -(tdiv*ngrid/2)+narray*(1/samplerate)
    t = t - np.min(t)
    
    return ch1,ch2,t

# Given a filepath string, returns 10x probe data from channels 1,2 and time data
def getData(FILEPATH):
    CH1,CH2,T = readFile(FILEPATH)
    CH1*=10
    CH2*=10
    return CH1,CH2,T

# Given a filepath string, returns the amplitude data from Channel 1
def getAmplitudes(FILEPATH):
    CH1,CH2,T = readFile(FILEPATH)
    CH1*=10
    CH2*=10
    xdots = np.argwhere(CH2 == 0)
    peaks = CH1[xdots]
    AMPLITUDES = peaks[1:]-peaks[:-1]
    return AMPLITUDES

# Given a filepath string, returns the log10(magnitude) vs. frequency data for a power spectrum plot
def getSpectrum(FILEPATH):
    CH1,CH2,T = readFile(FILEPATH)
    CH1*=10
    CH2*=10
    FREQUENCIES = fft.rfftfreq(CH1.size,T[1])
    temp = np.argwhere(FREQUENCIES>0)
    FREQUENCIES = np.log10(FREQUENCIES[temp])
    FFT = np.log10(np.abs(fft.rfft(CH1)))[temp]
    return FREQUENCIES,FFT