import numpy as np
import scipy.fft as fft
from scipy.signal import find_peaks as fp
from scipy.ndimage import gaussian_filter1d as gf1d
import struct

#---------------------------------------------------------------------#
#   chaoticPackage.py                                                 #
#                                                                     #
#   DESCRIPTION                                                       #
#   Reads .bin data generated by a SIGLENT SDS2352X-E Oscilloscope    #
#   Returns the either:                                               #
#   Amplitude data                                                    #
#   Power Spectrum frequency/magnitude data                           #
#   Channels 1,2 and time data                                        #
#                                                                     #
#   USAGE                                                             #
#   [ENSURE THAT BOTH THE REQUIREMENTS AND THIS SCRIPT                #
#    ARE IN THE SAME DIRECTORY]                                       #
#   import chaoticPackage as cp                                       #
#   amplitudes = cp.getAmplitudes("FILEPATH")                         #
#   freq,mag = cp.getSpectrum("FILEPATH")                             #
#   amplitudes = cp.getData("FILEPATH")                               #
#                                                                     #
#                                                                     #
#   Author: JAYSON WU                                                 #
#   Last Modified: March 5th, 2026                                    #
#---------------------------------------------------------------------#

# const parameters
ngrid = 14.0    # 14 grids horizontally on the oscilloscope screen
cpdiv = 25.0    # 25 data codes per div

# unit magnitude dictionary
mag = {
    5:1e-9,
    6:1e-6,
    7:1e-3,
    8:1e0,
    9:1e3,
    10:1e6,
    11:1e9
}

# Given a filepath string, returns 3 numpy arrays of data without probe magnification
def readFile(FILEPATH):
    file = open(FILEPATH,"rb")
    t = np.array([])
    ch1 = np.array([])
    ch2 = np.array([])
    file.seek(0x0,0)
    state1 = struct.unpack('<i',file.read(0x4))[0]
    file.seek(0x4,0)
    state2 = struct.unpack('<i',file.read(0x4))[0]
    
    file.seek(0xd4,0)
    tdiv = struct.unpack('<d',file.read(0x8))[0]
    file.seek(0xdc,0)
    tmag = mag[struct.unpack('<i',file.read(0x4))[0]]
    tdiv *= tmag
    
    file.seek(0xf4,0)
    wavelength = struct.unpack('<i',file.read(0x4))[0]
    narray = np.linspace(0,wavelength,wavelength)
    
    file.seek(0xf8,0)
    samplerate = struct.unpack('<d',file.read(0x8))[0]
    file.seek(0x100,0)
    sampleratemag = mag[struct.unpack('<i',file.read(0x4))[0]]
    samplerate *= sampleratemag
    
    if (state1 == 1):
        file.seek(0x10,0)
        ch1div = struct.unpack('<d',file.read(0x8))[0]
        file.seek(0x18,0)
        ch1mag = mag[struct.unpack('<i',file.read(0x4))[0]]
        ch1div *= ch1mag
        file.seek(0x800,0)
        ch1 = np.int8(np.fromfile(file,dtype=np.uint8,count=wavelength,offset=0)-128)*(ch1div/cpdiv)
        file.seek(0x50,0)
    
    if (state2 == 1):
        file.seek(0x20,0)
        ch2div = struct.unpack('<d',file.read(0x8))[0]
        file.seek(0x28,0)
        ch2mag = mag[struct.unpack('<i',file.read(0x4))[0]]
        ch2div *= ch2mag
        file.seek(0x800,0)
        if (state1 == 1):
            file.seek(wavelength,1)
        ch2 = np.int8(np.fromfile(file,dtype=np.uint8,count=wavelength)-128)*(ch2div/cpdiv)
        file.seek(0x60,0)
        
    t = -(tdiv*ngrid/2)+narray*(1/samplerate)
    t = t - np.min(t)
    
    return ch1,ch2,t

# Given a filepath string, returns 10x probe data from channels 1,2 and time data
def getData(FILEPATH):
    CH1,CH2,T = readFile(FILEPATH)
    CH1*=10
    CH2*=10
    return CH1,CH2,T

def getSmoothData(FILEPATH):
    CH1,CH2,T = readFile(FILEPATH)
    CH1*=10
    CH2*=10
    CH1 = gf1d(CH1,sigma=100)
    CH2 = gf1d(CH2,sigma=100)
    return CH1,CH2,T

# With a given FILEPATH string, assuming that the requested data was on CHANNEL 1, returns the BIFURCATION values
# Rv value is not given / dependent. That is up to the user.
def getAmplitudes(FILEPATH):
    CH1,__,__ = readFile(FILEPATH)
    CH1*=10.0
    n = len(CH1)//8
    CH1 = CH1[:n]
    SMOOTH = gf1d(CH1,sigma=10)
    N = fp(SMOOTH,prominence=0.1)[0]
    DATA = SMOOTH[N]
    return DATA

# Given a filepath string, returns the log10(magnitude) vs. frequency data for a power spectrum plot
def getSpectrum(FILEPATH):
    CH1,CH2,T = readFile(FILEPATH)
    CH1*=10
    CH2*=10
    FREQUENCIES = fft.rfftfreq(CH1.size,T[1])
    temp = np.argwhere(FREQUENCIES>0)
    FREQUENCIES = np.log10(FREQUENCIES[temp]).ravel()
    FFT = np.log10(np.abs(fft.rfft(CH1))[temp]).ravel()
    return FREQUENCIES,FFT

# Stores Rv and Amplitude data in the provided FILENAME as binary data
def pack(FILENAME,RV,DATA):
    file = open(FILENAME,"wb")
    SIZE = struct.pack("<i",len(RV))
    file.write(SIZE)
    for i in RV:
        TEMP = struct.pack("<f",i)
        file.write(TEMP)
    for i in DATA:
        TEMP = struct.pack("<f",i)
        file.write(TEMP)
        
# Unpacks binary file to grab Rv and amplitude data from a provided FILENAME string
def unpack(FILENAME):
    file = open(FILENAME,"rb")
    LEN = struct.unpack("<i",file.read(0x4))[0]
    file.seek(0x4,0)
    RV = np.float32(np.fromfile(file,dtype=np.float32,count=LEN,offset=0))
    DATA = np.float32(np.fromfile(file,dtype=np.float32,count=LEN))
    return RV,DATA